source $HOME/dot/osx/git-completion.bash

export VIRTUALENVWRAPPER_PYTHON="/usr/local/bin/python3"

source $HOME/dot/bash_custom

export CLICOLOR=1

export EDITOR="/Applications/Emacs.app/Contents/MacOS/Emacs -nw"

export PATH=$HOME/dot/osx/bin:$PATH

if [ -n "$VENVWRAPPER" ]; then
  alias mk27env="mkvirtualenv -p /usr/local/bin/python2.7"
  alias mk36env="mkvirtualenv -p /usr/local/bin/python3.6"
  alias mkvenv=mk36env
fi

alias sshig="et carljm.sb.facebook.com:8080 -c 'tmux -2CC new -A -s devserver'"
