autoload -U compinit
compinit

autoload -U promptinit
promptinit
prompt walters

export VIRTUALENVWRAPPER_PYTHON="/usr/local/bin/python3"

VENVWRAPPER=`which virtualenvwrapper.sh 2>/dev/null`
if [ -n "$VENVWRAPPER" ]; then
  export WORKON_HOME=$HOME/.venvs
  export PROJECT_HOME=$HOME/projects
  source $VENVWRAPPER
fi

export HISTCONTROL=ignoreboth
export HISTSIZE=100000
export HISTFILESIZE=100000

export PATH=$HOME/dot/osx/bin:$HOME/dot/bin:$HOME/.local/bin:$HOME/.cargo/bin:/usr/local/go/bin:$HOME/go/bin:$PATH

export GOPATH=$HOME/go

eval "$(hub alias -s)"

export CLICOLOR=1

export EDITOR="vim"

alias sshig="et carljm.sb.facebook.com:8080 -c 'tmux -2CC new -AD -s devserver'"

export LDFLAGS="-L/usr/local/opt/zlib/lib -L/usr/local/opt/sqlite/lib -L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/zlib/include -I/usr/local/opt/sqlite/include -I/usr/local/opt/openssl/include"

[[ -s $HOME/.pythonz/etc/bashrc ]] && source $HOME/.pythonz/etc/bashrc

if [ -n "$VENVWRAPPER" ]; then
    alias mk27env="mkvirtualenv -p $(pythonz locate 2.7.16)"
    alias mk36env="mkvirtualenv -p $(pythonz locate 3.6.8)"
    alias mk37env="mkvirtualenv -p $(pythonz locate 3.7.3)"
    alias mkvenv=mk37env
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# use ctrl+left/right arrows to jump between words
bindkey "\e[5C" forward-word
bindkey "\e[5D" backward-word

# use up/down arrows to autocomplete command from history
bindkey "\e[B" history-search-forward
bindkey "\e[A" history-search-backward

# better colors
export TERM='xterm-color'
alias ls='ls -G'
alias ll='ls -lG'
export LSCOLORS="ExGxBxDxCxEgEdxbxgxcxd"
export GREP_OPTIONS="--color"
